# Generated by Django 5.1.6 on 2025-02-28 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        # 1. DownloadableFileモデルを作成
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField()),
                ('is_downloaded', models.BooleanField(default=False)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        # 2. 既存のDownloadRecordを削除（データがすでにある場合はバックアップしてください）
        migrations.DeleteModel(
            name='DownloadRecord',
        ),
        # 3. 新しいDownloadRecordモデルを作成
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='files.downloadablefile')),
            ],
        ),
    ]
