# Generated by Django 5.1.6 on 2025-03-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20250301_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
